### ISSUE TITLE
DatabricksConfig does not recognize environment variables

### ISSUE THREAD

**Issue by nija-at** [databricks/databricks-sdk-java#109]
Using version 0.1.1 on a simple Scala program:

```scala
    println(s"env host: ${sys.env.get("DATABRICKS_HOST").get}")
    println(s"env token: ${sys.env.get("DATABRICKS_TOKEN").get}")
    val config = new DatabricksConfig()
    println(s"host: ${config.getHost}")
    println(s"token: ${config.getToken}")
```

The output is

```
env host: http://foo.databricks.com
env token: test
host: null
token: null
```

**Comment by nfx** [comment]
@nija-at did you try calling `.resolve()` on `DatabricksConfig`?

**Comment by nija-at** [comment]
Yes, that worked. Thanks.

I assume there's good reason to have a separate `resolve()` method instead of resolving in the constructor.

It would be good to throw an error if any value is requested before `resolve()` is called at least once.
