### ISSUE TITLE
[Feature Request] Add support for configuring a proxy against the httpClient used by Databricks

### ISSUE THREAD

**Issue by Hidoshi1** [databricks/databricks-sdk-java#111]
Currently `DatabricksConfig` allows setting the httpClient, but I am unable to initialize a `com.databricks.sdk.core.http.HttpClient` instance, let alone one with a proxy. It would be extra nice if we could configure the proxy for each http scheme. I would like to explicitly force proxy type HTTP, similar to this code:

```
import java.net.http.HttpClient

    private fun getWhitelistProxyHttpClient(): HttpClient {
        val proxyAddress = InetSocketAddress(proxyHost, proxyPort)

        val proxySelector = object : ProxySelector() {
            override fun select(uri: URI): List<Proxy> {
                return listOf(Proxy(Proxy.Type.HTTP, proxyAddress))
            }

            override fun connectFailed(uri: URI?, sa: SocketAddress?, ioe: IOException?) {
                log.error { "Proxy connection failed: $uri $sa $ioe" }
            }
        }

        return HttpClient.newBuilder()
            .version(HttpClient.Version.HTTP_2)
            .proxy(proxySelector)
            .build()
    }
```

**Comment by mgyucht** [comment]
I think we should be able to use `.useSystemProperties()` which is built-in to the current Apache Commons client we're using, and then you can set `"https.proxyHost"` and `"http.proxyPort"` system properties to use your proxy. If you're already using an HTTP proxy, you should be able to do something like:
```java
java -Dhttps.proxy="$HTTPS_PROXY" -cp ... MyApp
```

**Comment by mgyucht** [comment]
@Hidoshi1 can you see if the proposed solution in #241 would resolve your need?

**Comment by Hidoshi1** [comment]
@mgyucht that looks great! Thanks!
