### ISSUE TITLE
Noob question: having issues with running examples in intellij community edition

### ISSUE THREAD

**Issue by fordpw** [databricks/databricks-sdk-java#151]
I've download the zip unzipped, everything seems to compile/build without error and I cannot run any of the examples. I am not versed in maven and/or intellij, but used to be a java programmer many years ago. I learn by example and tutorials on maven and intellij are too generalized to apply to this problem, please advise?

**Comment by fordpw** [comment]
![image](https://github.com/databricks/databricks-sdk-java/assets/4064304/95dfeb20-53e6-448a-88c5-4b1b1a7dea05)

**Comment by mgyucht** [comment]
Did you figure this out, or did you accidentally close this issue?
