### ISSUE TITLE
[ISSUE] Thread leakage in the JDBC driver when connection cannot be established

### ISSUE THREAD

**Issue by krocodl** [databricks/databricks-sdk-java#186]
https://community.databricks.com/t5/data-engineering/thread-leakage-when-connection-cannot-be-established/td-p/39435

**Comment by mgyucht** [comment]
@krocodl thank you for reporting this. This issue pertains to the JDBC driver, but this repo is the Java SDK. We currently don't have an open-source repo or issue tracker for the JDBC driver to my knowledge, but will CC the relevant folks here. cc @gopalldb @bogdanghit @ccstevens
