### ISSUE TITLE
[ISSUE] OOM while loading a lot of data through JDBC

### ISSUE THREAD

**Issue by krocodl** [databricks/databricks-sdk-java#187]
https://community.databricks.com/t5/data-engineering/oom-while-loading-a-lot-of-data-through-jdbc/td-p/49096

**Comment by mgyucht** [comment]
@krocodl thank you for reporting this. This issue pertains to the JDBC driver, but this repo is the Java SDK. We currently don't have an open-source repo or issue tracker for the JDBC driver to my knowledge, but will CC the relevant folks here. cc @gopalldb @bogdanghit @ccstevens
