### ISSUE TITLE
[ISSUE] listSecrets returns null if no secrets are found in a scope

### ISSUE THREAD

**Issue by MichaelJHaywood** [databricks/databricks-sdk-java#197]
**Description**
If I make a call to get a list of secrets in a scope, it returns null if no secrets are found. 

**Reproduction**
Returns null if no secrets are found
```
String scopeName = "example";
workspaceClient.secrets().createScope(scopeName );
workspaceClient.secrets().listSecrets(scopeName ); // Returns null
```
Returns a secret if a secret is found
```
String scopeName = "example";
workspaceClient.secrets().createScope(scopeName );
workspaceClient.secrets()
          .putSecret(new PutSecret()
                  .setScope(scopeName)
                  .setKey("key")
                  .setStringValue("value")
          );
workspaceClient.secrets().listSecrets(scopeName );  // Successfully returns a secret
```

**Expected behavior**
An empty result instead of null.

**Is it a regression?**
Unknown.

**Other Information**
 - OS: Windows 10
 - Version: 10.0.19043 Build 19043

**Comment by MichaelJHaywood** [comment]
@mgyucht I believe I was printing the returned iterable and it was null. It appeared to be behaving differently to other list() calls as I normally convert it to a stream using:
```
StreamSupport.stream(iterable.spliterator(), false)
```
but it was failing as it was null. 

I can't check right now to be certain sorry!

**Comment by MichaelJHaywood** [comment]
@mgyucht 
We've had a similar error occur but for clusters. If you get a list of clusters and none are found, it returns null instead of an empty iterable. 
The sql warehouse method correctly returns an empty iterable.

**Comment by mgyucht** [comment]
Thanks for this. I've identified the root cause and made a PR to address it: #266.
