### ISSUE TITLE
[FEATURE] Support uploading files in dbfs.put() method

### ISSUE THREAD

**Issue by mosopeogundipe** [databricks/databricks-sdk-java#231]
**Problem Statement**
Currently in WorkspaceClient().dbfs().put(), only a string `contents` is supported. However the actual endpoint supports passing a file as a multipart/form-data, as mentioned [here](https://kb.databricks.com/dbfs/upload-large-files-using-dbfs-api-20-and-powershell). We need a convenient way to upload large files and the current `put()` method doesn't have that since the string `contents` cannot exceed 1MB.

**Proposed Solution**
Add a file as an extra parameter in the [Put](https://github.com/databricks/databricks-sdk-java/blob/main/databricks-sdk-java/src/main/java/com/databricks/sdk/service/files/Put.java) object, so that we can do something like `Put().setFile(new File("/path/to/file/on/local"))`

**Comment by tanmay-db** [comment]
Hi @mosopeogundipe, thanks for reaching out. Due to other higher priority items and low bandwidth we won't be able to  prioritise this feature request. Can you please the Volumes and Files API, they support uploading files for much larger sizes.

**Comment by mgyucht** [comment]
@mosopeogundipe FYI, there is `w.dbfs().write(Path p, byte[] bytes)` that will handle this. Try
```java
Path localPath = Paths.get(...);
byte[] bytes = Files.readAllBytes(localPath);
Path remotePath = "dbfs:/my/path";
w.dbfs().write(remotePath, bytes);
```
