### ISSUE TITLE
[ISSUE] Clusters listing not working

### ISSUE THREAD

**Issue by arturowczarek** [databricks/databricks-sdk-java#341]
**Description**
The Paginator for Clusters (and other APIs) never ends when iterated over.
The reason is the line `if (token == null) {` in api.java.tmpl. It should be `if ("".equals(token)) {` instead. According to the REST documentation (and my experiments) the last page has next page token equal to empty string.

**Reproduction**

```
@Slf4j
class DatabricksErrorTest {

  @Test
  void testNotWorking() {
    DatabricksConfig config =
        new DatabricksConfig()
            .setHost("xxx.azuredatabricks.net")
            .setToken("mytoken");

    WorkspaceClient workspace = new WorkspaceClient(config);
    Iterable<ClusterDetails> clusterDetails = workspace.clusters().list(new ListClustersRequest());
    int iteration = 0;
    for (ClusterDetails clusterDetail : clusterDetails) {
      // This prints forever and the application never ends. It loops over the clusters over and over again.
      log.info("Iteration {}", iteration++);
    }
  }
}
```

**Expected behavior**
The `Iterable` should iterate over every catalog once and let the program continue instead of iterating again.

**Is it a regression?**
It used to work on 0.4.0 but it was long time ago (when the SDK didn't use `Paginator`)

**Debug Logs**
Not important

**Other Information**
 - OS: macOS
 - Version: 0.30.0

**Additional context**
No

**Comment by arturowczarek** [comment]
I could fix it but I don't know what tool I should use to regenerate the classes. If someone could teach me, then I can do it.

**Comment by arturowczarek** [comment]
@mgyucht Maybe you can instruct me how to regenerate the classes? I know the generator can be found in https://github.com/databricks/databricks-sdk-go/blob/main/openapi/gen/main.go, but can't find the OpenAPI document for Databricks API. There used to be possibility to download it from [Databricks API Reference](https://docs.databricks.com/api/workspace/introduction), but it seems gone.

**Comment by hectorcast-db** [comment]
Hi @arturowczarek 
Thanks for raising this. 
The OpenAPI documentation and the generator are not public (https://github.com/databricks/databricks-sdk-go/blob/main/openapi/gen/main.go is only a part of it). 

I have opened a PR to fix this
https://github.com/databricks/databricks-sdk-java/pull/343
